### ISSUE TITLE
TE transcripts fasta file needed to Mode 2.

### ISSUE THREAD

**Issue by Ifengel** [OliveiraDS-hub/ChimeraTE#14]
Hello, 

I want to use chimeraTE mode 2 to identify chimeras without taking into account the reference genome. Specifically, I want to do it in mouse (mm10). However, I don't know where I can find the file with transposable element transcripts in fasta format. 

I have seen that some people get this file directly from GTF using gffRead, but I don't know if this will work in this case. 

Where could I find or how could I create this file?

Thank you very much in advance, 

Ivan

**Comment by OliveiraDS-hub** [comment]
Dear @Ifengel, there is an easy way to produce the fasta file with all TE sequences in the reference genome.

For mm10, you can access this link from UCSC genome browser:

https://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/

Then, you can download this file:

`wget https://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/mm10.fa.out.gz`

This file is the standard output from RepeatMasker, containing the position for all repeat sequences, including TEs.

You also need the genome fasta file:

`wget https://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/mm10.fa.gz`

Finally, you can use the handy script in ChimeraTE's util folder: [rmout2fasta.sh](https://github.com/OliveiraDS-hub/ChimeraTE/blob/main/util/rmout2fasta.sh)

This is the command line to do the conversion:

`gunzip mm10.fa.out.gz`
`gunzip mm10.fa.gz`

`bash ChimeraTE/util/rmout2fasta.sh --genome mm10.fa --rm mm10.fa.out --out mm10_TEs.fa`

This command line will create the fasta file required to run ChimeraTE mode 2.

I'm not a specialist on mouse TEs. Please, take a look if you don't have unexpected sequences (such as non-TEs) in your `mm10_TEs.fa` file. You can do it with: `grep '>' mm10_TEs.fa | sort | uniq`

Keep in mind that bigger TE files will increase processing time. If you are not interested in a few class or family of TEs, remove them.

In addition, if you are using the parameter `--assembly`, don't forget to apply `--ref_TEs` to specify that you are working with mouse, otherwise ChimeraTE will try to mask Drosophila TEs in your transcripts assembled with Trinity. Note: increasing RAM and threads you save you a lot of time.

Let me know if it worked for you.

Cheers

**Comment by OliveiraDS-hub** [comment]
I assume this issue has been solved.

Feel free to reopen it if you still have any questions.
