### ISSUE TITLE
chimTE_mode1.py file not found

### ISSUE THREAD

**Issue by Lynuxoo** [OliveiraDS-hub/ChimeraTE#5]
I'm trying to run the chimTE_mode1.py script from the ChimeraTE repository, but I'm getting an error message that says "python3: can't open file 'chimTE_mode1.py': [Errno 2] No such file or directory." I've already navigated to the ChimeraTE directory and activated the conda environment as instructed in the documentation, but I still can't find the chimTE_mode1.py file.

I suspect that I might have missed a step during the installation process or that I'm in the wrong directory. Can someone please provide some guidance on how to resolve this issue?

Thanks in advance for your help!

**Comment by OliveiraDS-hub** [comment]
Dear @Lynuxoo 

If your conda environment has been created and activated sucessfully with chimeraTE.yml, then you must have all dependencies to run chimeraTE. You've got this error just because we are still updating the github repository, and the script was missing.
I apologize for that!
ChimeraTE Mode 1 should now run normally. Test it with the example data.

Cheers

**Comment by Lynuxoo** [comment]
Dear @OliveiraDS-hub 

Thank you so much for your previous response, I was able to run the program successfully. 

However, I have encountered a new issue. I noticed that ChimeraTE requires a genome file and an input file, but I already have STAR alignment results. Is there a way to use my existing alignment results as input for ChimeraTE instead of re-aligning with STAR?

Thanks for any suggestions or pointers to relevant documentation.
